trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      options: '-Pnative -Dquarkus.native.container-build=true --batch-mode'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: Docker@2
    inputs:
      containerRegistry: 'ACRServiceConnection'
      repository: '$(REPOSITORY)'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile.native'
      buildContext: '.'
      addPipelineData: false

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureResourceManager'
      azureSubscription: '$(AZURE_SUBSCRIPTION)'
      appType: 'webAppContainer'
      WebAppName: '$(APP)'
      DockerNamespace: '$(REGSITRY)'
      DockerRepository: '$(REPOSITORY)'